### ISSUE TITLE
Can't run the imagine command

### ISSUE THREAD

**Issue by insan000** [lucidrains/deep-daze#15]
Hello,
Deep daze looks amazing and I want to give it a try. But I'm having an error about Cuda. The GPU I'm using is gtx1660 and I've already installed Cuda. Any help would be appreciated! :)

https://ibb.co/mNHRkQG
https://ibb.co/HF6HYsH

**Comment by jnelson16** [comment]
You likely need to install the correct version of PyTorch, I ran into the same issue. Instructions for installing are [here](https://pytorch.org/). I installed the CUDA=11.0 version and now it runs.

**Comment by insan000** [comment]
That solves the problem. But this time I got another Cuda error (out of memory). It only works when I reduce the number of layers. I guess I'll stick with the Google Collab.
Thanks mate 💯
