### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by 1sacred1** [lucidrains/deep-daze#71]
I'm running into an issue when using "imagine" in my prompt. This is my first time using something like python so bear with me.

**RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 5.98 GiB already allocated; 100.56 MiB free; 5.99 GiB reserved in total by PyTorch)**

I'm not really understanding what the issue is here, I would think that 8GB is enough.

**Comment by NuclearSurvivor** [comment]
it means the command you are trying to run will take more vram than you have and it wont run.
basically if you just said 
> `imagine "whatever you put"`
then you are not able to run the program

**Comment by 1sacred1** [comment]
im trying to use the flag "--deeper" do I not have enough vram for that? if not, how much is needed?

**Comment by NuclearSurvivor** [comment]
probably 16gb, I have a 2080super and I tried to use the --deeper flag, but it gave me the same message.

I was only able to change the number of epochs and number of iterations successfully.

**Comment by afiaka87** [comment]
There's a large list of of memory optimization techniques on the README (the front page of the documentation). I'll go get em so people dont have to go hunting if they arrive here from google. brb

**Comment by afiaka87** [comment]
Something I left it out in the README, you actually can pull off the the `--deeper` flag on an 8 GiB card @NuclearSurvivor (that's how much the 2080 has right? Great card by the way. Shame they didn't ship with more VRAM bc they're plenty fast). You will need to set a decently low `--image_width`. Probably something like less than ~300px. But it's not all that bad and if you want to you can just run the image through a super resolution net to get it back to a higher resolution. It also runs _significantly_ faster at 256px than at 512px

**Comment by NuclearSurvivor** [comment]
ok so you would use `imagine "whatever" --num_layers=24 --batch_size=1`. and ok i will try to render in 256px

just to be clear this is how i would write it `imagine "whatever" --image_width=256 --num_layers=24 --batch_size=1`

**Comment by afiaka87** [comment]
> ok so you would use `imagine "whatever" --num_layers=24 --batch_size=1`. and ok i will try to render in 256px
> 
> just to be clear this is how i would write it `imagine "whatever" --image_width=256 --num_layers=24 --batch_size=1`
> 
> Im running this right now `imagine "steve jobs tripping on LSD, sitting watching rick and morty in a cozy living room." --image_width=256 --num_layers=24 --batch_size=1`

Yep that's exactly the syntax! You can use a cool pip program called gpustat to monitor your VRAM levels as it runs. If you find you have room to spare, you can up the --num_layers value until you run out of memory. In general, you want to get as close to 32 (the value --deeper uses) as possible. But that's tough on 8 GiB. lemme know how it goes!

**Comment by afiaka87** [comment]
also! While said to use a batch_size of 1, that's _very_ low. I would increase it to 4 or more. One cool trick you can do to get higher quality out of a lower batch size is to use, for instance `--batch_size=4 --gradient_accumulate=8`. The higher your gradient_accumulate_every, the longer each iteration will take, but it will try to make each iteration more accurate. You could think of it as trying to split your batch size into chunks in order to fit it into VRAM (although that approximation isn't how things actually work, it's good enough for thinking at a high level.)

**Comment by NuclearSurvivor** [comment]
wouldnt do that `imagine "extraterrestrial beings" --batch_size=32 --num_layers=44 --epochs=8` didnt work for me i got the runtime cuda out of memory error

**Comment by afiaka87** [comment]
He didn't explicityl mention this, but he's also using --image_width=256 and --gradient_accumulate_every=1.

The full command would technically be: 
`imagine "extraterrestrial beings" --batch_size=32 --num_layers=44 --epochs=8 --image_width=256 --gradient_accumulate_every=1.`
Does that work?

**Comment by afiaka87** [comment]
So, if you run the `pip install gpustat; gpustat -i` stuff from earlier, what you'll find is that on windows or linux, your GPU is actually already using about 2 GiB of VRAM. This is normal and it's the result of your desktop manager and general operating system environment needing to store things in VRAM for snappy responses in the GUI.

Often, we're working in linux environments on a server that are "headless". They dont have a desktop environment. You just run command line. As such they have zero GPU usage and that lets you use more of your total VRAM. If you are on linux and would like a desktop environment that uses less VRAM, you can check out XFCE, i3, etc. They will use something like 500 - 300 MiB. You can also just hit alt-f2 at login, kill gnome-desktop, or whatever you're using and just run everything in that terminal session.

**Comment by afiaka87** [comment]
> wouldnt do that `imagine "extraterrestrial beings" --batch_size=32 --num_layers=44 --epochs=8` didnt work for me i got the runtime cuda out of memory error
> `imagine "extraterrestrial beings" --gradient_accumulate_every=16 --batch_size=8 --num_layers 15` worked for me though
> do you think this will give me a nice clean image?

You shouldn't go beneath 16 layers. It's the default and should probably be the minimum, honestly. It just barely starts to give you good results. Going to, say 24 with a slightly slower image_width than you're currently using would be worth the decrease in resolution. 

This is sort of part of the process with machine learning. VRAM is a precious resource in ML and this stuff uses a lot of it. As such it requires tinkering with a few parameters. These parameters are always a tradeoff between memory usage, total runtime, and the accuracy of the neural net. In exchange for being patient enough to find decent parameters, you get a state-of-the-art open source image generation for free. Pretty cool stuff but I'll admit it takes some patience.

**Comment by NuclearSurvivor** [comment]
> You shouldn't go beneath 16 layers. It's the default and should probably be the minimum, honestly. It just barely starts to give you good results. Going to, say 24 with a slightly slower image_width than you're currently using would be worth the decrease in resolution.
> 
> This is sort of part of the process with machine learning. VRAM is a precious resource in ML and this stuff uses a lot of it. As such it requires tinkering with a few parameters. These parameters are always a tradeoff between memory usage, total runtime, and the accuracy of the neural net. In exchange for being patient enough to find decent parameters, you get a state-of-the-art open source image generation for free. Pretty cool stuff but I'll admit it takes some patience.

I was willing to have the patience to install this, and it took all last night and when I put an issue in the channel, the dev immediately fixed both of the issues I had and other people were having in less than an hour so that was pretty cool. Unfortunately, I am not on Linux and am subjected to the 2 GB of VRAM usage by default. L

**Comment by afiaka87** [comment]
Gradient accumulate is kinda magical. It has zero impact on memory, but it will take a bit longer if you increase it.

**Comment by soberirving** [comment]
@NuclearSurvivor @afiaka87 My cuda GPU utilization is 0%...Although the reply of torch.cuda.is_available() is TRUE...Could you please share your conda list? I want to know which part do I miss...Thank you very much!
