### ISSUE TITLE
Cuda errors 

### ISSUE THREAD

**Issue by Burg3red** [lucidrains/deep-daze#92]
Hey, I'm trying to set up deep daze and or Big sleep on my computer to create some art and I have almost no coding experience especially surrounding python. I am able to install Big Sleep and Deep daze on my anaconda environment however I get Cuda errors every time I try to use the imagine or dream commands. I would really appreciate some help troubleshooting.

**Comment by maxcan7** [comment]
I am also getting CUDA errors.

**Comment by maxcan7** [comment]
In the google colab notebook they address this, but I haven't yet accounted for this locally.

> # Restart after running this cell!
> 
> You must run this cell and then restart and rerun everything for the PyTorch version to be correct. Otherwise the model will run but not produce any meaningful output.

```
import subprocess

CUDA_version = [s for s in subprocess.check_output(["nvcc", "--version"]).decode("UTF-8").split(", ") if s.startswith("release")][0].split(" ")[-1]
print("CUDA version:", CUDA_version)

if CUDA_version == "10.0":
    torch_version_suffix = "+cu100"
elif CUDA_version == "10.1":
    torch_version_suffix = "+cu101"
elif CUDA_version == "10.2":
    torch_version_suffix = ""
else:
    torch_version_suffix = "+cu110"

! pip install torch==1.7.1{torch_version_suffix} torchvision==0.8.2{torch_version_suffix} -f https://download.pytorch.org/whl/torch_stable.html ftfy regex
```

**Comment by maxcan7** [comment]
If it's a CPU/GPU/hardware thing, I may need to pull out my [Jetson](https://developer.nvidia.com/embedded/jetson-nano-developer-kit) for this 0.o. Was hoping to play around with this before work but I guess I'll have to do it later.

**Comment by maxcan7** [comment]
> This will require that you have an Nvidia GPU

I should really read the documentation more carefully haha

**Comment by Burg3red** [comment]
Yeah for me installing the newest version of torch worked for me, Imagine now works but I also have big sleep installed and dream gives me Cuda memory errors which I'm not sure how to fix because I've already got 8 GB of v ram.

**Comment by Burg3red** [comment]
Also, do you know how to get these to be higher quality images than 500x500 or is that the only size it renders in?

**Comment by maxcan7** [comment]
> Yeah for me installing the newest version of torch worked for me, Imagine now works but I also have big sleep installed and dream gives me Cuda memory errors which I'm not sure how to fix because I've already got 8 GB of v ram.

For my own clarity, you mean you're on a machine that has a GPU, but still needed to do that?

> Also, do you know how to get these to be higher quality images than 500x500 or is that the only size it renders in?

Have not had a chance to investigate yet, but if you figure it out let me know.

Anyway, so this "issue" can be closed then?

**Comment by benstuart0** [comment]
CUDA isn't available on MacOS after Intel 10.13. I'm having the same problem and am thinking DeepDaze just isn't mac compatible :( I would love to know a way around this though.

**Comment by staberas** [comment]
> If it's a CPU/GPU/hardware thing, I may need to pull out my [Jetson](https://developer.nvidia.com/embedded/jetson-nano-developer-kit) for this 0.o. Was hoping to play around with this before work but I guess I'll have to do it later.

Tested with a Jetson nano 2GB and it gives the same error

**Comment by maxcan7** [comment]
> Tested with a Jetson nano 2GB and it gives the same error

Dang I still haven't gotten around to trying this out for myself but that's disappointing to hear. Hopefully, it's just something that requires some finagling and not a hardware incompatibility thing :(...

**Comment by staberas** [comment]
> Dang I still haven't gotten around to trying this out for myself but that's disappointing to hear. Hopefully, it's just something that requires some finagling and not a hardware incompatibility thing :(...
 
definitely not hardware issue , jetson has cuda cores, im guessing it just some missing library or some pytorch addon to make it work on the jetson
